[build]
builder = "DOCKERFILE"
dockerfilePath = "deploy/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[variables]
HOST = "0.0.0.0"
PORT = "3080"
